<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2019 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace Raylin666\Utils\Coroutine;

use Swoole\Coroutine\WaitGroup as SwooleCoroutineWaitGroup;

/**
 * Class WaitGroup
 * @package Raylin666\Utils\Coroutine
 */
class WaitGroup extends SwooleCoroutineWaitGroup
{
    /**
     * 增加计数
     * @param int $delta
     */
    public function add(int $delta = 1): void
    {
        parent::add($delta); // TODO: Change the autogenerated stub
    }

    /**
     * 标明任务已完成
     */
    public function done(): void
    {
        parent::done(); // TODO: Change the autogenerated stub
    }

    /**
     * 等待所有任务完成恢复当前协程的执行
     * @param float $timeout
     * @return bool
     */
    public function wait(float $timeout = -1): bool
    {
        return parent::wait($timeout); // TODO: Change the autogenerated stub
    }
}